dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- 3.8-dev
install:
- pip install -r requirements/tests.txt
- pip install -e .
script: pytest
deploy:
  provider: pypi
  user: plangrid
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: HgqYcE6hrhWg/orHzgI6yOnC0+B3K3zCXWFH0MvJtHcWiksbOwaFstriHcD3aIz2burRY+vWqQcf/PAfDuE2WLKQ/z4uNESXd09+GRGYfQkfDAUP1oocfjb2bSLJeRwflMDVAuipg8YZtTs6YhAzjFn8ZjtDNZAXS2qRJoX4606efGIK8Kfp+aPy5Pcshc6JGVoip5JMv/509JZASprDmK4mS7/xVcdTWTOfmM1fNDbW9XGj1k39raT2/xOvc+QqFX+J05rJr8bxtf3/7uY0QwS9h3StmTRSjU54aIgPwNUUFEMnntwUhdorjQQbEWFk3OBu87DkFz1XUw2Di6aOcDG0scI7t/Lpa9qSglDE0Q8f0di2hdQP21m8+/547WO6YYf8sg4AE5NAHvPu66+FWvnKPppXJE+chFw+BWcltXjHnRhVIzl2y8BbogEDRYkYBy04vclCFiURMw0vf1w4c5hD6m6u/GSOtwRMwdEmm0bjJ7Smq3XVnuo7uTFN+/CTbdq/973SiMaSplhm2ceeGezvDPcViMDily1zTq+txocCioBQdLl40891oA7I37dSStkqZ15nf9CY89gZEP2LqunzqPxxdm62UI7TjmFeL4VCBiZgdY4P/uKLogA5orB2rwmt+wJlKAAy8y2X/Atycl4SlsvZ1QhJqWiO+zZde30=
